services:
  db:
    image: postgres:16
    container_name: simulti_db
    environment:
      POSTGRES_DB: simulti
      POSTGRES_USER: simultiuser
      POSTGRES_PASSWORD: simultipassword
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - simultinet
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: simulti_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/simultinet
      SPRING_DATASOURCE_USERNAME: simultiuser
      SPRING_DATASOURCE_PASSWORD: simultipassword
      SERVER_PORT: 8080
    networks:
      - simultinet
      - proxy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # Backend is served at https://simulti.santoriello.ch/api
      - "traefik.http.routers.simulti-backend.rule=Host(`simulti.santoriello.ch`) && PathPrefix(`/api`)"
      - "traefik.http.routers.simulti-backend.entrypoints=websecure"
      - "traefik.http.routers.simulti-backend.tls.certresolver=le"

      - # Remove `/api` before forwarding to Springboot
      - "traefik.http.middlewares.simulti-backend-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.simulti-backend.middlewares=simulti-backend-strip"

      - # Springboot listens on port 8000
      - "traefik.http.services.simulti-backend.loadbalancer.server.port=8080"

  frontend:
    build: ./frontend
    container_name: simulti_frontend
    depends_on:
      - backend
    networks:
      - proxy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simulti-frontend.rule=Host(`simulti.santoriello.ch`)"
      - "traefik.http.routers.simulti-frontend.entrypoints=websecure"
      - "traefik.http.routers.simulti-frontend.tls.certresolver=le"
      - "traefik.http.services.simulti-frontend.loadbalancer.server.port=80"

volumes:
  pgdata:

networks:
  simultinet:
  proxy-network:
    external: true
